### ISSUE TITLE
pushed my solution without pulling. there may be some merge conflicts, need to p

### ISSUE THREAD

**Issue by RealGavinPrice** [samiyazaki/Testing_take_a_walk#5]
There may be some merge conflicts with what you pushed up but stuff seems to work. i had to remove the "type" datapoint in the js script link in index.html to get the google map to function but that was the only thing that wasn't working.

**Comment by samiyazaki** [comment]
I adjusted merge conflicts so they would all work, I undid some of the push changes in favor of alternate HTML to ensure program still functioned
