### ISSUE TITLE
spotify playlist post request syntax issue

### ISSUE THREAD

**Issue by RealGavinPrice** [samiyazaki/Testing_take_a_walk#7]
do we need to add a token fetch for the embedded iframe player? the iframe embed skips tracks and lands on the 3rd, which only plays for 10 seconds. the fetch request is for license and returns a 400, "client error" basically. "strict-origin-when-cross-origin"

Request URL: https://gue1-spclient.spotify.com/widevine-license/v1/audio/license
Request Method: POST
Status Code: 400 
Remote Address: 35.186.224.16:443
Referrer Policy: strict-origin-when-cross-origin

**Comment by samiyazaki** [comment]
Looks like you sorted it properly, closing issue d/t fix. Good work
